// Tests for the LAS reader, run with `npm test` (Node 18+, no dependencies).
//
// The fixtures in test_data/ are generated by test_data/make_test_las.R and
// contain a flat ground surface (class 2) and three tree clusters (class 5).
// Formats 2, 3, 7 and 8 additionally carry colour: brown on the ground,
// green on the canopy.
//
// Reading classification or colour from the wrong byte would collapse the two
// groups or return noise, so these assertions pin the per-format offsets.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { parseLAS } from "../src/lasParser.js";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "..", "test_data");

const load = (name) => {
  const path = join(dataDir, name);
  if (!existsSync(path)) {
    throw new Error(
      `${name} not found. Generate the fixtures first:\n` +
      `  R -e 'setwd("."); source("test_data/make_test_las.R")'`
    );
  }
  const buf = readFileSync(path);
  return parseLAS(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
};

const cases = [
  { file: "test_fmt0.las", format: 0, version: "1.2", rgb: false },
  { file: "test_fmt1.las", format: 1, version: "1.2", rgb: false },
  { file: "test_fmt2.las", format: 2, version: "1.2", rgb: true },
  { file: "test_fmt3.las", format: 3, version: "1.2", rgb: true },
  { file: "test_fmt6.las", format: 6, version: "1.4", rgb: false },
  { file: "test_fmt7.las", format: 7, version: "1.4", rgb: true },
  { file: "test_fmt8.las", format: 8, version: "1.4", rgb: true },
];

for (const c of cases) {
  test(`${c.file}: header`, () => {
    const p = load(c.file);
    assert.equal(p.ver, c.version);
    assert.equal(p.hasRGB, c.rgb);
    assert.equal(p.n, 560, "all points should be read without subsampling");
    assert.equal(p.n, p.nOrig);
  });

  test(`${c.file}: classification read from the right byte`, () => {
    const p = load(c.file);
    const classes = new Set(p.classification);
    assert.deepEqual([...classes].sort((a, b) => a - b), [2, 5],
      "expected exactly ground (2) and high vegetation (5)");

    let ground = 0, canopy = 0;
    for (const v of p.classification) {
      if (v === 2) ground++;
      else if (v === 5) canopy++;
    }
    assert.equal(ground, 200);
    assert.equal(canopy, 360);
  });

  test(`${c.file}: ground sits below the canopy`, () => {
    const p = load(c.file);
    let gSum = 0, gN = 0, cSum = 0, cN = 0;
    for (let i = 0; i < p.n; i++) {
      if (p.classification[i] === 2) { gSum += p.z[i]; gN++; }
      else { cSum += p.z[i]; cN++; }
    }
    assert.ok(cSum / cN > gSum / gN + 5,
      "canopy points should be well above ground points");
  });

  if (c.rgb) {
    test(`${c.file}: colour read from the right byte`, () => {
      const p = load(c.file);
      const mean = (cls, ch) => {
        let s = 0, k = 0;
        for (let i = 0; i < p.n; i++) {
          if (p.classification[i] === cls) { s += p[ch][i]; k++; }
        }
        return s / k;
      };
      // ground is brown (red dominant), canopy is green (green dominant)
      assert.ok(mean(2, "r") > mean(2, "g"), "ground should be red-dominant");
      assert.ok(mean(5, "g") > mean(5, "r"), "canopy should be green-dominant");
      // and the two groups must be clearly different, not noise
      assert.ok(Math.abs(mean(2, "r") - mean(5, "r")) > 40);
    });
  }
}

test("coordinates are returned relative to a double-precision origin", () => {
  const p = load("test_fmt0.las");
  assert.equal(typeof p.ox, "number");
  assert.equal(typeof p.oy, "number");
  let maxAbs = 0;
  for (let i = 0; i < p.n; i++) maxAbs = Math.max(maxAbs, Math.abs(p.x[i]));
  assert.ok(maxAbs < 1e4, "stored x should be a local offset, not an absolute easting");
});

test("a file that is not LAS is rejected", () => {
  const junk = new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]).buffer;
  assert.throws(() => parseLAS(junk));
});
